#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $VAMPIRES_REPO == "Vampiresbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0F1cmFYTmV0d29yay9BdXJhWFVzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $VAMPIRES_REPO == "Vampiresbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0F1cmFYTmV0d29yay9BdXJhWFVzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $VAMPIRES_REPO =~ $regex ]]
    then
        if [[ $VAMPIRES_REPO_BRANCH ]]
        then
            echo "${VAMPIRES_REPO}/archive/${VAMPIRES_REPO_BRANCH}.zip"
        else
            echo "${VAMPIRES_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0F1cmFYTmV0d29yay9BdXJhWFVzZXJib3QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="Vampiresbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    VAMPIRESPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $VAMPIRESPATH
    echo "    Starting Vampiresbot    "
    echo "
    __   __              _ __  _                _          _   
\ \ / / __ _  _ __  | '_ \(_) _ _  ___  ___| |__  ___ | |_ 
 \   / / _` || '  \ | .__/| || '_|/ -_)(_-/|  _ \/ _ \|  _|
  \_/  \__/_||_|_|_||_|   |_||_|  \___|/__/|____/\___/ \__|
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
